// Copyright SwifterTheDragon, 2025. All Rights Reserved.

namespace SwifterTheDragon.VerboseSourceRevisionIdBuilder.SourceGenerator.Core
{
    /// <summary>
    /// Provides helper methods for source generation,
    /// such as making auto-generated code header comments.
    /// </summary>
    internal static class GeneratorHelper
    {
        #region Methods
        /// <summary>
        /// Makes a code header comment to label auto-generated code.
        /// </summary>
        /// <param name="toolName">
        /// The name of the tool that generated the code.
        /// Specifically, the AssemblyName.
        /// </param>
        /// <param name="toolVersion">
        /// The version of the tool that generated the code.
        /// Specifically, the AssemblyVersion.
        /// </param>
        /// <param name="sourceFileName">
        /// The name of the source file that generated the code.
        /// </param>
        /// <returns>
        /// A header comment for labelling auto-generated code as auto-generated
        /// when scanning the contents of a source code file.
        /// </returns>
        internal static string MakeAutoGeneratedCodeHeader(
            string toolName,
            string toolVersion,
            string sourceFileName = null)
        {
            // 80 characters per line is a common standard.
            string autoGeneratedCodeHeader = "//----------------------------"
                + "--------------------------------------------------\n"
                + "// <auto-generated>\n"
                + "//     This code was generated by \""
                + toolName
                + "\"\n"
                + "//     Version: "
                + toolVersion
                + "\n//\n";
            if (!string.IsNullOrWhiteSpace(
                value: sourceFileName))
            {
                autoGeneratedCodeHeader += "//     from "
                    + sourceFileName
                    + '\n';
            }
            autoGeneratedCodeHeader += "//\n"
                + "//     Changes to this file may cause incorrect behaviour and will be lost if\n"
                + "//     the code is regenerated.\n"
                + "// </auto-generated>\n"
                + "//----------------------------"
                + "--------------------------------------------------\n";
            return autoGeneratedCodeHeader;
        }
        /// <summary>
        /// Makes a code footer comment to label auto-generated code.
        /// </summary>
        /// <param name="toolName">
        /// The name of the tool that generated the code.
        /// Specifically, the assembly name.
        /// </param>
        /// <param name="generatorClassName">
        /// The name of the class that generated the code.
        /// </param>
        /// <returns>
        /// A footer comment for labelling auto-generated
        /// code as auto-generated.
        /// </returns>
        internal static string MakeAutoGeneratedFooter(
            string toolName,
            string generatorClassName)
        {
            string autoGeneratedFooter = "// Generated by \""
                + toolName
                + "\"'s \""
                + generatorClassName
                + "\" class.\n";
            return autoGeneratedFooter;
        }
        #endregion Methods
    }
}
